function y = SynthesizeText(h0, x0, RNN, n)
b = RNN.b; % m, 1
c = RNN.c; % K, 1
U = RNN.U; % m, K
W = RNN.W; % m, m
V = RNN.V; % K, m
h = h0;
x = x0;
y = zeros(1, n);
% Similar to ComputeCost function, but with one difference,
% the xnext need to be generated by x
for i=1:n % n: the length of the text
    a = W*h+U*x+b;
    h = tanh(a);
    o = V*h+c;
    p = softmax(o);
    %  randomly select a character based on the output probability scores p:
    cp = cumsum(p); % compute the vector containing the cumulative sum of the probabilities
    a = rand; % generate a random draw, a, from a uniform distribution in the range 0 to 1
    ixs = find(cp-a >0);
    ii = ixs(1);
    K = size(c, 1);
    % Y is the one-hot encoding of each sampled character:
    x = onehot(ii, K);
    y(i) = ii;
end

